config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :talks

  get 'home/dashboard'
	devise_scope :user do
	  authenticated :user do
	     get '/users/sign_out' => 'devise/sessions#destroy'
	    root  'home#dashboard', as: :authenticated_root
	  end
	  unauthenticated do
	    root 'devise/sessions#new', as: :unauthenticated_root
	  end
	end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :talk
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :user
  has_many :attendees, dependent: :destroy
  accepts_nested_attributes_for :attendees, :allow_destroy => true,:reject_if => :all_blank  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :company, :bio])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]
  def index
    @talks = Talk.all
  end

  def new
    @talk = Talk.new
    @talk.attendees.build
  end

  def show
  end

  def edit
  end

  def create
    @talk = Talk.new talks_params
    @talk.user_id = current_user.id
    binding.pry
    respond_to do |format|    
      if @talk.save
        format.html { redirect_to talks_path, notice: 'Talks created Succesfully.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @talk.update(talks_params)
        format.html { redirect_to talks_path, notice: 'Talks Updated Succesfully.' }
      else
        format.html { render :edit }
      end
    end    
  end

  def destroy
      binding.pry
      respond_to do |format|
      if params[:attendee_id]
        @talk.attendees.destroy( params[:attendee_id])
         format.html { redirect_to talk_path(params[:id]), notice: 'Attendee was successfully destroyed.' }
      else
        @talk.destroy
         format.html { redirect_to talks_path, notice: 'Talks was successfully destroyed.' }
      end
    end    
  end

  private

  def set_talk
    @talk = Talk.find(params[:id])
  end
  def talks_params
    params.require(:talk).permit(:title, :abstract, :room,  attendees_attributes: [:id,:name, :company, :email, :registered])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/home/dashboard.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row mt-6 updates">
                <div class="col-md-2 p-0">
                    <h5>Latest Updates</h5>
                </div>
                <div class="col-md-9 p-0 scroll">
                    <marquee><a href="viewall-updates.html" class="mr-2"> Create an Rails application to create data structures mirroring talks and attendees</marquee>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h4 class="page-title mb-0">Dashboard</h4>
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header-primary">Talks</div>
                        <div class="card-body">Add Talk</div>
                        <div class="card-body">Edit Talk</div>
                        <div class="card-body">Show Talk and its Attendees Details</div>
                        <div class="card-body">Destroy talks</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header-info">Attendees</div>
                        <div class="card-body">Delete Attendees</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">© 2019 Record Management <span class="d-none d-sm-inline-block">- All Rights Reserved</span></footer>

app/views/layouts/_left_sidebar.html.erb
<div class="left side-menu">
    <div class="slimscroll-menu" id="remove-scroll">
        <div id="sidebar-menu">
            <ul class="metismenu" id="side-menu">
                <li class="menu-title">Main</li>
                <li><a href="/" class="waves-effect"><i class="dripicons-meter"></i> <span>Dashboard</span></a></li>
                <li><a href="/talks" class="waves-effect"><i class="dripicons-article"></i><span> Talks <span class="float-right menu-arrow"><i class="mdi mdi-chevron-right"></i></span></span></a>
                </li>
                </li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<script>
$(document).on("turbolinks:load", function() {
    window.jQuery.MainApp.init()
})
</script>

app/views/layouts/_topbar.html.erb
<div class="topbar">
    <div class="topbar-left">
        <a href="/" class="logo"><img src="<%= asset_path 'record.png' %>" alt="" height="50" class="logo-large">
            <img src="/assets/record.png" alt="" height="22" class="logo-sm"></a>
    </div>
    <nav class="navbar-custom">
        <ul class="navbar-right d-flex list-inline float-right mb-0">
            <li class="list-inline-item dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false"><img src="<%= asset_path 'profile-pic.png' %>" alt="user" class="rounded-circle"> <span class="d-none d-md-inline-block ml-1">Welcome
                        <%= current_user.name %><i class="mdi mdi-chevron-down"></i></span></a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated profile-dropdown">
                    <a class="dropdown-item" href="documents/TaxPayerUserManual_GST_0.4.pdf" target="_blank"><i class="dripicons-user text-muted"></i> User Manual</a>
                    <a class="dropdown-item" href="<%#= users_change_password_path %>"><i class="dripicons-lock text-muted"></i> Change Password</a>
                    <div class="dropdown-divider"></div><a rel="nofollow" data-method="delete" class="dropdown-item" href="/users/sign_out"><i class="dripicons-exit text-muted"></i> Logout </a>
                </div>
            </li>
        </ul>
        <ul class="list-inline menu-left mb-0">
            <li class="float-left">
                <button class="button-menu-mobile open-left waves-effect"><i class="mdi mdi-menu"></i></button>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecordsManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="fixed-left">
    <div id="wrapper">
      <% if current_user %>
        <%= render "layouts/topbar" %>
        <%= render "layouts/left_sidebar" %>
      <% end %>
        <%= yield %>
        <% if current_user %>
         <%= render "layouts/footer" %>
        <% end %>
    </div>
  </body>
</html>

app/views/talks/_form.html.erb
<%= nested_form_for(talk, local: true) do |form| %>
<div class="row" id="original-invoice">
    <div class="col-md-4">
        <div class="form-group">
            <label class="required">Title</label>
            <%= form.text_field :title, class: "form-control" , placeholder: "Title", :required => true%>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label class="">Abstract</label>
            <%= form.text_field :abstract, class: "form-control" , placeholder: "Abstract",:required => true %>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label class="required">Room</label>
            <%= form.text_field :room, class: "form-control" , placeholder: "Room",:required => true %>
        </div>
    </div>
</div>
<!-- end row -->
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <table id="datatable1" class="table table-striped table-bordered dashboard-table dt-responsive nowrap scroll-table datatable_datatable table-input" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Company</th>
                                    <th>Email</th>
                                    <th>Registered Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                <%= form.fields_for :attendees, :wrapper => false do |attendee| %>
                                <tr>
                                    <td>
                                        <%= attendee.text_field :name, class: 'form-control', placeholder: "Name", :required => true %>
                                    </td>
                                    <td>
                                        <%= attendee.text_field :company, class: 'form-control', placeholder: "Company", :required => true %>
                                    </td>
                                    <td>
                                        <%= attendee.email_field :email, class: 'form-control', placeholder: "Email", :required => true %>
                                    </td>
                                    <td>
                                        <%= attendee.date_field :registered, class: 'form-control', placeholder: "Date", :required => true %>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-12">
                                <%= form.link_to_add "Add", :attendees, data: { target: ".datatable_datatable" }, class: "btn btn-primary mb-2 float-right" %>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end row -->
<div class="row">
    <div class="col-md-12">
        <div class="form-group mb-3 mt-5">
            <div class="text-center">
                <button type="reset" class="btn btn-secondary waves-effect m-l-5">Clear</button>
                <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/talks/edit.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h4 class="page-title mb-0">Edit Talk</h4>
                                <span><%= flash[:notice] %></span>
                                <ul>
                                <% @talk.errors.full_messages.each do |msg| %>
                                  <li><%= msg %></li>
                                <% end %>
                                </ul>                                
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Edit Talk</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="">Talk</div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                     <%= render 'form', talk: @talk %>
                </div>
            </div>
        </div>
    </div>
</div> 

app/views/talks/index.html.erb
<div class="content-page">
  <!-- Start content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <div class="page-title-box">
            <div class="row align-items-center">
              <div class="col-md-8">
                <h4 class="page-title mb-0">Talks</h4>
                <ol class="breadcrumb m-0">
                  <li class="breadcrumb-item"><a href="">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Talks</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end row -->
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header">
              <div class="row">
                <div class="col-md-6">
                  <div class="">Talks</div>
                </div>
              </div>
            </div>
            <div class="card-body">
              <div class="row mb-3 align-items-center">
                <div class="col-md-8">
                  <div class="row">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="pull-right">
                    <div class="btn-group">
                      <button type="button" class="btn btn-outline-primary">Action</button>
                      <button type="button" class="btn btn-outline-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="/talks/new"><i class="dripicons-user text-muted mr-2"></i>ADD</a>
                        <div class="dropdown-divider"></div>                        
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  
                  <table id="example" class="table table-bordered dt-responsive table-striped nowrap customdatatable" width="100%">
                    <thead>
                      <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Abstract</th>
                        <th>Room</th>
                        <th>Number Of Attendee</th>                      
                        <th data-priority="2">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @talks.each do |talk| %>
                      <tr>
                        <td>
                          <input class="editor-active" data-talk-id="<%= talk.id %>" type="checkbox">
                        </td>
                        <td>
                          <%= talk.title.present? ? talk.title : "NA"  %>
                        </td>
                        <td>
                          <%= talk.abstract.present? ? talk.abstract : "NA"  %>
                        </td>
                        <td>
                          <%= talk.room.present? ? talk.room : "NA" %>
                        </td>  
                        <td>
                          <%= talk.attendees.count %>
                        </td> 
                        <td>
                          <a href="<%= talk_path(talk) %>" class="btn btn-primary btn-circle" data-toggle="tooltip" data-placement="top" title="">
                            <i class="dripicons-document-edit"></i>Show
                          </a>                          
                          <a href="<%= edit_talk_path(talk) %>" class="btn btn-primary btn-circle" data-toggle="tooltip" data-placement="top" title="">
                            <i class="dripicons-document-edit"></i>Edit
                          </a>
                          <%= link_to 'Delete', talk, method: :delete, data: { confirm: 'Are you sure?'} ,class: "btn btn-danger waves-effect waves-light text-white" %>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end row -->
    </div>
    <!-- container-fluid -->
  </div>
  <!-- content -->
</div>
<script>
$(document).ready(function() {
  var table = $('#example').DataTable({
    select: {
      style: 'multi',
      selector: '.select-checkbox',
      items: 'row',
    },
    responsive: {
      details: {
        type: 'column',
        target: 0
      }
    },
    columnDefs: [{
        targets: 0,
        className: 'control'
      },
      {
        targets: 1,
        //className: 'select-checkbox'
      },
      {
        targets: [0, 1],
        orderable: false
      }
    ],
    order: [2, 'asc']
  });
  $('#exampleSelectAllTableContent').on('click', function() {
    // Check/uncheck all checkboxes in the table
    var rows = $('#example').DataTable().rows({ 'search': 'applied' }).nodes();
    $('input[type="checkbox"]', rows).prop('checked', this.checked);
  });
  $('#delete_b2b').click(function(event) {
    event.preventDefault();
    var selectedVendors = []
    $(".editor-active[type='checkbox']:checked").map(function(index, element) {
      selectedVendors.push($(element).data('b2bId'))
    })
    if (selectedVendors.length > 0) {
      var AUTH_TOKEN = $('meta[name=csrf-token]').attr('content');
      if (confirm('Are you sure you want to delete?')) {
        $.ajax({
          url: "/b2bs/destroy_selected.json",
          data: { vendor_ids: selectedVendors },
          method: 'POST',
          datatype: 'SCRIPT',
          success: function(response) {
            window.location.reload()
          },
          error: function(error) {
            alert("Unable to process your request. Please try again later!");
          }
        })
      }
    } else {
      alert("Please select atleast one Vendor to delete!");
    }
  });

});
</script>























<table>
  <thead>
    <tr>
		<th>title</th>
		<th>Abstract</th>
		<th>room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @talks.each do |talks| %>
      <tr>
        <td><%= talks.title %></td>
        <td><%= talks.abstract %></td>
        <td><%= talks.room %></td>
        <td><%= link_to 'Show', talks %></td>
        <td><%= link_to 'Edit', edit_talk_path(talks) %></td>
        <td><%= link_to 'Destroy', talks, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talk', new_talk_path %>

app/views/talks/new.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h4 class="page-title mb-0">ADD Talk</h4>
                                <span><%= flash[:notice] %></span>
                                <ul>
                                <% @talk.errors.full_messages.each do |msg| %>
                                  <li><%= msg %></li>
                                <% end %>
                                </ul>                                
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Add Talk</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="">Talk</div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                     <%= render 'form', talk: @talk %>
                </div>
            </div>
        </div>
    </div>
</div> 

app/views/talks/show.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h4 class="page-title mb-0">Talks</h4>
                                <span>
                                    <%= flash[:notice] %></span>
                                <ul>
                                    <% @talk.errors.full_messages.each do |msg| %>
                                    <li>
                                        <%= msg %>
                                    </li>
                                    <% end %>
                                </ul>
                                <ol class="breadcrumb m-0">
                                    <li class="breadcrumb-item"><a href="">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Talk Show</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="">Talks Show</div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-3" id="gstin-customer">
                                    <div class="form-group">
                                        <label class="">Title :-</label>
                                        <%= @talk.title %>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="">Abstract :- </label>
                                        <%= @talk.abstract %>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="">Room :- </label>
                                        <%= @talk.room  %>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="">Number Of Attendee :-</label>
                                        <%= @talk.attendees.count %>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <table id="" class="table table-bordered dt-responsive table-striped nowrap customdatatable" width="100%">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Company</th>
                                                <th>Email</th>
                                                <th>Registered</th>
                                                <th data-priority="2">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <% @talk.attendees.each do |at| %>
                                            <tr>
                                                <td>
                                                    <%= at.name.present? ? at.name : "NA"  %>
                                                </td>
                                                <td>
                                                    <%= at.company.present? ? at.company : "NA"  %>
                                                </td>
                                                <td>
                                                    <%= at.email.present? ? at.email : "NA" %>
                                                </td>
                                                <td>
                                                    <%= at.registered.present? ? at.registered : "NA" %>
                                                </td>
                                                <td>
                                                    <%= link_to "Delete Attendee", talk_path(id:  @talk.id, attendee_id: at.id), :confirm => 'Are you sure?', :class => "btn btn-danger waves-effect waves-light text-white", :method => :delete %>
                                                </td>
                                            </tr>
                                            <% end %>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/talks/update.html.erb
<h1>Talks#update</h1>
<p>Find me in app/views/talks/update.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>